### ISSUE TITLE
not able to create pull request in empty repository

### ISSUE THREAD

**Issue by ossdev07** [jnr/jnr-a64asm#1]
please create README file so that i can create pull request for the code submission

**Comment by rhenwood-arm** [comment]
@headius : I am very interested in seeing the jnr-a64asm code progress into this repo. Can you create a suitable file so the PR can be issued?

**Comment by ossdev07** [comment]
@headius : please do needful changes in this repo because there is delay in submission of the changes in **jnr-ffi** repo too

**Comment by headius** [comment]
Very sorry! I had vacation and nobody else maintaining JNR apparently saw these messages.

I have initialized the repo and we can move forward!
